version: '3'

services:
  frontend:
    image: babrock/contest-frontend:0.0.2
    container_name: contest-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 5173:5173
  backend:
    image: babrock/contest-backend:0.0.5
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
    environment:
      spring_profiles_active: prod
      spring_sql_init_mode: always
  mysql-db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: contest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
